import { expect, test } from '@playwright/test';

test('cadastro confirmado, carteira, lançamento e detalhe com nota', async ({ page }) => {
  const email = `e2e-${Date.now()}@example.com`;
  await page.goto('/login?mode=reset&token=token-do-link', { waitUntil: 'domcontentloaded' });
  const themeToggle = page.getByRole('button', { name: 'Ativar tema claro' });
  await expect(themeToggle).toBeVisible();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'orbital');
  const orbitalBackground = await page.locator('body').evaluate((element) => getComputedStyle(element).backgroundColor);
  await themeToggle.click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'classic');
  const classicBackground = await page.locator('body').evaluate((element) => getComputedStyle(element).backgroundColor);
  expect(classicBackground).not.toBe(orbitalBackground);
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'classic');
  await page.getByRole('button', { name: 'Ativar tema orbital' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'orbital');
  await expect(page.getByRole('heading', { name: 'Redefinir senha' })).toBeVisible();
  await expect(page.getByLabel('Token')).toHaveValue('token-do-link');
  await page.goto('/login', { waitUntil: 'domcontentloaded' });
  await page.getByRole('button', { name: /cadastre-se/i }).click();
  await page.getByLabel('Nome').fill('Pessoa E2E');
  await page.getByLabel('E-mail').fill(email);
  await page.getByLabel('Senha').fill('senha-segura');
  await page.getByRole('button', { name: 'Criar conta' }).click();
  await expect(page.getByRole('heading', { name: 'Confirme seu e-mail' })).toBeVisible();
  await page.getByRole('button', { name: 'Confirmar e entrar' }).click();

  await page.getByRole('link', { name: 'Perfil' }).click();
  await expect(page.getByRole('heading', { name: 'Perfil' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Ativar tema claro' })).toBeVisible();
  await page.getByRole('link', { name: 'Voltar', exact: true }).click();

  await page.getByRole('button', { name: 'Criar carteira' }).click();
  await page.getByPlaceholder('Nome da nova carteira').fill('Carteira E2E');
  await page.getByRole('button', { name: 'Criar', exact: true }).click();
  const form = page.locator('form.stack-form');
  const purchaseHeight = (await form.boundingBox())!.height;
  for (const type of ['DIVIDENDO', 'JCP', 'BONIFICACAO', 'DESDOBRAMENTO']) {
    await form.getByLabel('Tipo').selectOption(type);
    expect((await form.boundingBox())!.height).toBe(purchaseHeight);
    if (type === 'JCP') {
      const dateBox = (await form.getByLabel('Data').boundingBox())!;
      const unitPriceBox = (await form.getByLabel('Preço unitário (opcional)').boundingBox())!;
      const descriptionBox = (await form.getByLabel('Descrição (opcional)').boundingBox())!;
      expect(unitPriceBox.y - (dateBox.y + dateBox.height)).toBeLessThan(56);
      expect(descriptionBox.y).toBeGreaterThan(unitPriceBox.y + unitPriceBox.height);
      expect(descriptionBox.y - (unitPriceBox.y + unitPriceBox.height)).toBeLessThan(56);
    }
  }
  await form.getByLabel('Tipo').selectOption('COMPRA');
  await form.getByLabel('Ativo').fill('PETR4');
  await page.getByLabel('Quantidade').fill('10.12345678');
  await page.getByLabel('Valor total').fill('1000.12345678');
  await page.getByLabel('Preço unitário (opcional)').fill('98.79');
  await page.getByRole('button', { name: 'Salvar lançamento' }).click();
  await expect(page.getByRole('status')).toContainText('sucesso');
  await expect(page.locator('.activity-icon').first()).toHaveText('C');
  await expect(page.locator('.activity-value').first())
    .toContainText('10,12345678 un. · Preço unitário R$ 98,79');
  await expect(page.locator('.metric').filter({ hasText: 'Custo de aquisição' }).locator('strong'))
    .toHaveText(/R\$\s*1\.000,12/);
  await page.getByRole('link', { name: 'Posições da carteira', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Posições da carteira' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Ativar tema claro' })).toBeVisible();
  await expect(page.locator('app-record-form')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('PETR4');
  await page.getByRole('link', { name: 'Voltar à carteira' }).click();
  await page.getByRole('link', { name: 'Proventos', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Proventos' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Ativar tema claro' })).toBeVisible();
  const incomeRecordForm = page.locator('app-record-form');
  await expect(incomeRecordForm.getByLabel('Tipo').locator('option')).toHaveCount(2);
  const incomeAsset = incomeRecordForm.getByLabel('Ativo');
  const incomeAssetId = await incomeAsset.locator('option', { hasText: /^PETR4 ·/ }).getAttribute('value');
  await incomeAsset.selectOption(incomeAssetId!);
  await incomeRecordForm.getByLabel('Valor total').fill('10');
  await incomeRecordForm.getByLabel('Preço unitário (opcional)').fill('1');
  await incomeRecordForm.getByRole('button', { name: 'Salvar lançamento' }).click();
  await expect(incomeRecordForm.getByRole('status')).toContainText('sucesso');
  await expect(page.locator('.income-page-history tbody')).toContainText('PETR4');
  await page.getByRole('link', { name: 'Voltar à carteira' }).click();
  const recordsPanel = page.locator('#lancamentos .panel.wide');
  await expect(recordsPanel.getByRole('link', { name: 'Lançamentos', exact: true }))
    .toHaveAttribute('href', /\/wallets\/[^/]+\/records/);
  await recordsPanel.getByRole('link', { name: /Ver histórico completo/ }).click();
  await expect(page.getByRole('heading', { name: 'Histórico de lançamentos' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Ativar tema claro' })).toBeVisible();
  await expect(page.locator('.topbar-menu').getByRole('link')).toHaveCount(4);
  const recordFormPanel = (await page.locator('#novo-lancamento').boundingBox())!;
  const recordsFilterPanel = (await page.locator('.records-filters').boundingBox())!;
  expect(recordFormPanel.x).toBeLessThan(recordsFilterPanel.x);
  await expect(page.locator('tbody tr')).toHaveCount(2);
  await expect(page.locator('tbody')).toContainText('PETR4');
  const recordsFilters = page.locator('.records-filter');
  await recordsFilters.getByLabel('Tipo').selectOption('VENDA');
  await page.getByRole('button', { name: 'Filtrar', exact: true }).click();
  await expect(page.getByText('Nenhum lançamento encontrado para os filtros selecionados.')).toBeVisible();
  await page.getByRole('button', { name: 'Limpar filtros' }).click();
  await expect(page.locator('tbody tr')).toHaveCount(2);
  await page.getByRole('link', { name: 'Novo lançamento' }).click();
  await expect(page.getByRole('heading', { name: 'Adicionar lançamento' })).toBeVisible();
  await expect(page.locator('app-record-form')).toBeVisible();
  await page.getByRole('link', { name: 'Voltar à carteira' }).click();
  await expect(page.locator('#lancamentos').getByRole('heading', { name: 'Lançamentos' })).toBeVisible();
  const deleteTrigger = page.locator('.activity').filter({ hasText: 'Compra · PETR4' })
    .getByRole('button', { name: 'Excluir lançamento' });
  await deleteTrigger.focus();
  await page.keyboard.press('Enter');
  const deleteModal = page.getByRole('dialog');
  await expect(deleteModal).toBeVisible();
  await expect(deleteModal.getByRole('heading', { name: 'Excluir lançamento?' })).toBeVisible();
  await expect(deleteModal).toContainText('PETR4');
  const cancelDeletion = deleteModal.getByRole('button', { name: 'Manter lançamento' });
  const confirmDeletion = deleteModal.getByRole('button', { name: 'Excluir lançamento' });
  await expect(cancelDeletion).toBeFocused();
  await confirmDeletion.focus();
  await page.keyboard.press('Tab');
  await expect(cancelDeletion).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  await expect(confirmDeletion).toBeFocused();
  await cancelDeletion.click();
  await expect(deleteModal).not.toBeVisible();
  await expect(deleteTrigger).toBeFocused();
  await form.getByLabel('Tipo').selectOption('VENDA');
  const petr4 = await form.locator('select[formcontrolname="assetId"] option', { hasText: /^PETR4 ·/ })
    .getAttribute('value');
  await form.getByLabel('Ativo').selectOption(petr4!);
  await form.getByLabel('Quantidade').fill('999999');
  await form.getByLabel('Valor total').fill('1');
  await page.getByRole('button', { name: 'Salvar lançamento' }).click();
  await expect(form.locator('.form-message-slot .alert')).toBeVisible();
  expect((await form.boundingBox())!.height).toBe(purchaseHeight);
  await page.getByRole('link', { name: 'PETR4' }).click();
  await expect(page.getByRole('heading', { name: 'PETR4' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Ativar tema claro' })).toBeVisible();
  await page.getByLabel('Conteúdo').fill('Nota criada no fluxo E2E');
  await page.getByRole('button', { name: 'Adicionar' }).click();
  await expect(page.getByText('Nota criada no fluxo E2E')).toBeVisible();
});
